log:
  level: INFO

entryPoints:
  web:
    address: ':80/tcp'
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ':443/tcp'
    http:
      middlewares:
        - compress@file
        - hsts@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: "hainhome.duckdns.org"
            sans:
              - "*.hainhome.duckdns.org"
    http3: {}

api:
  dashboard: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: hhai2105@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: duckdns
        resolvers: 
          - "1.1.1.1:53"
          - "8.8.8.8:53"

providers:
  docker:
    watch: true
    network: traefik
    exposedByDefault: false
  file:
    filename: traefik_dynamic.yml

serversTransport:
  insecureSkipVerify: true


